### ISSUE TITLE
7p 11.2.1 开启抢红包按钮被title挡住了

### ISSUE THREAD

**Issue by jerezw** [kevll/WeChatRedEnvelopesHelper#10]

**Comment by kevll** [comment]
这个问题已修复，请安装一下最新的ipa，我做了一些优化体验更好，而且增加了指定群聊过滤功能，已测试iOS9-iOS11系统。
ipa百度网盘[下载链接](https://pan.baidu.com/s/1bKlctg)  密码: grdx

**Comment by liuxiaokun** [comment]
@kevll 网盘失效了 能不能重新发一下

**Comment by kevll** [comment]
@liuxiaokun 我刚试了网盘没有失效啊，能打开的，https://pan.baidu.com/s/1bKlctg  密码: grdx
