### ISSUE TITLE
iOS 11.2.6 用impactor出错

### ISSUE THREAD

**Issue by BakaYang** [kevll/WeChatRedEnvelopesHelper#102]
appid和密码输入没错

<img width="420" alt="7fed477d-9353-47ed-89ba-2d6e7e2bcf0a" src="https://user-images.githubusercontent.com/23470990/37140403-98cf0562-22ec-11e8-846d-2e920d1b84c9.png">

**Comment by kevll** [comment]
可注册新的苹果账号使用

**Comment by BakaYang** [comment]
双重认证关了之后还是会报这个错，我又申请了一个appid，出现
<img width="420" alt="40a4c0e6-eeb9-42e3-afca-25543f810aca" src="https://user-images.githubusercontent.com/23470990/37275849-3ff551d0-261b-11e8-8b93-0eee66a158de.png">
又在win电脑上试了下，可以安装成功

**Comment by kevll** [comment]
遇到这个问题，Revoke Certificates一下就好了
