### ISSUE TITLE
git同步问题，代码变更处出现<<<<<<< HEAD

### ISSUE THREAD

**Issue by a569922982** [kevll/WeChatRedEnvelopesHelper#104]
<<<<<<< HEAD
THEOS_DEVICE_IP = 192.168.0.102
=======
THEOS_DEVICE_IP = 192.168.5.25

DEBUG = 0

ARCHS = armv7 armv7s arm64
>>>>>>> 14b3d449a06c72fb56714fe3d5a240cf0e1bf756

麻烦大哥修复下。。。。

**Comment by kevll** [comment]
已经修复
