### ISSUE TITLE
反台跟鎖屏下沒法搶

### ISSUE THREAD

**Issue by long0302** [kevll/WeChatRedEnvelopesHelper#11]
我ios9.3.1
微信版本6.6.0

**Comment by kevll** [comment]
请安装一下最新的ipa，我做了一些优化体验更好，而且增加了指定群聊过滤功能，已测试iOS9-iOS11系统。
ipa百度网盘[下载链接](https://pan.baidu.com/s/1bKlctg)  密码: grdx
