### ISSUE TITLE
iPhoneX无法后台运行，后台收不到微信消息，并且视频语音都无提示

### ISSUE THREAD

**Issue by QiPhonepplus** [kevll/WeChatRedEnvelopesHelper#120]
iPhoneX无法后台运行，后台收不到微信消息，而且语音视频电话都没提示，这个问题不知道其他人有没有，我重装了好几次，都如此！

**Comment by kevll** [comment]
新版微信已经去掉了CallKit，所以在后台语音视频电话都没提示，这个是跟随苹果政策调整的
