### ISSUE TITLE
iphone 5, ios 9.3.2 Error

### ISSUE THREAD

**Issue by Kejiasir** [kevll/WeChatRedEnvelopesHelper#14]
Error 
installation.cpp:42
failed to find matching arch for 64-bit mach-o input file /private/var/installd/library/caches/com.apple.mobile.installd.staging/temp.izluwv/extracted/payload/extender.app/extender

iphone 5, ios 9.3.2

另外, 请问是要把原来的微信 APP 卸载掉, 再安装 WeChat-kevll.ipa 这个吗?

**Comment by kevll** [comment]
请问你使用Mac还是win安装的？
我刚刚用iphone5试了一下，是可以安装成功的。
另外不需要把原来的微信APP删除掉，是可以双开的。

**Comment by Kejiasir** [comment]
是用的 Mac, 手机是没越狱的

**Comment by Kejiasir** [comment]
从XX助手上面下载越狱版ipa --> 解压缩 --> 拷贝WeChatRedEnvelopesHelper.dylib和libsubstate.dylib到Frameworks目录 --> 向WeChat二进制文件注入dylib -> 更改 WeChatRedEnvelopesHelper.dylib 依赖 --> 打包重签名安装

请问这个是啥意思啊, 一直没看懂

**Comment by Kejiasir** [comment]
每次都是到验证程序这个步骤就报错啦, 咋整呢?~~
<img width="479" alt="qq20180105-111737 2x" src="https://user-images.githubusercontent.com/14361443/34594102-bd72d6d4-f194-11e7-98b1-112d864062cb.png">

**Comment by Kejiasir** [comment]
@kevll 估计是ios 9.x版本太低吧, 装不了重签名的工具, 刚用另一个ios 11.x手机试了可以装上, 但是不知道怎么重签名; 
我直接把你那个 WeChat-kevll.ipa 拖到 impactor 就安装到手机上了, 但是不会抢红包, 完全没反应, 是因为没有重签名的原因吗?

**Comment by kevll** [comment]
@Kejiasir 请尝试V2.0.1新版本
