### ISSUE TITLE
锁屏和后台貌似无用？

### ISSUE THREAD

**Issue by dakezuo** [kevll/WeChatRedEnvelopesHelper#15]

**Comment by kevll** [comment]
是越狱手机还是非越狱？手机型号以及系统版本？
检查一下微信助手设置里面的后台模式有没有打开，
检查一下系统设置里面的微信有没有打开后台刷新，
想要支持后台和锁屏模式这两个都需要打开。

**Comment by dakezuo** [comment]
@kevll 是非越狱手机，iPhone6s ios11.2.1,后台模式和后台刷新都开着，也没有杀死进程

**Comment by kevll** [comment]
微信消息通知有没有关？手机锁屏能不能收到红包的推送消息？

**Comment by dakezuo** [comment]
能收到，但是必须点进去微信界面才会去抢，而且，目前被封号了，说是非法客户端 @kevll

**Comment by kevll** [comment]
@tomatobin 收到的是本地推送，要开启后台模式并且保持微信进程不kill掉
