### ISSUE TITLE
./plist.hpp:201 not PLIST_STRING

### ISSUE THREAD

**Issue by ruicky** [kevll/WeChatRedEnvelopesHelper#16]
# 硬件信息
Cydia Impactor： MAC版0.9.42
IOS：10.3.3 未越狱
机器：iphone7Plus
微信版本：6.6.2
# 报错
![error](http://ww3.sinaimg.cn/large/0060lm7Tly1fn3fmxekhij30nc0bs40g.jpg)

# 说明
使用 Impactor 导入以后报错。如图。
目前机器本身的微信也不能用了。

**Comment by ruicky** [comment]
虽然 报错，但是打开新导入的微信包 还是可用的 不知道为什么。。。

**Comment by ClayGuitar** [comment]
iPhone6   10.3.1也遇到了这个问题
