### ISSUE TITLE
使用Impactor安装报错

### ISSUE THREAD

**Issue by lifeMiik** [kevll/WeChatRedEnvelopesHelper#17]
IOS10.3 微信版本6.6 ，这个是什么原因呢，谢谢。
![1f2dd1ad-4c14-4b95-9c54-9a80b0a1a6b9](https://user-images.githubusercontent.com/13726235/34512443-95b1cfb2-f09d-11e7-905a-64f779a33c86.png)

**Comment by kevll** [comment]
报这个错误是可以忽略的，你看看手机上是不是已经安装好了微信？

**Comment by lifeMiik** [comment]
是的，已经信任了，但是设置并没有出现微信助手设置。
