### ISSUE TITLE
能否增加虚拟定位功能

### ISSUE THREAD

**Issue by iangsb** [kevll/WeChatRedEnvelopesHelper#19]
谢谢

**Comment by kevll** [comment]
是指发送位置信息的时候增加虚拟定位，地图选点吗？

**Comment by iangsb** [comment]
是的，虚拟定位，如果加进去我贡献你一杯咖啡，嘻嘻

**Comment by kevll** [comment]
可以，下一版本增加，敬请期待

**Comment by iangsb** [comment]
能在一个手机里面装两个微信吗？都需要你的抢红包功能

**Comment by kevll** [comment]
1.手动将WeChat-kevll.ipa改为WeChat-kevll.zip，然后再解压缩
2.进入解压缩的文件夹，搜索Info.plist文件然后用编辑器打开
3.将`<key>CFBundleIdentifier</key>
    <string>com.kevll.wechat</string>` 的这段中的“com.kevll.wechat” 修改为 “xxx.xxx.xxx”后保存文件
4.将文件夹重新进行ZIP压缩，再将压缩后的后缀名修改为ipa
5.用这个新的ipa就可以在同一个手机上再装一个了，用同样的方法可实现多开微信

**Comment by iangsb** [comment]
不会封号吧

**Comment by kevll** [comment]
我自己的微信已经用很久了没出过问题，而且微信一般也不会随便封号的。

**Comment by iangsb** [comment]
能方便加你的微信吗？
