### ISSUE TITLE
make package install 失败

### ISSUE THREAD

**Issue by Paladinfeng** [kevll/WeChatRedEnvelopesHelper#2]
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:10: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

**Comment by kevll** [comment]
theos环境装好了吗？
检查一下THEOS环境变量是否配置好了
进入终端输入
`echo $THEOS`
看是否正确配置了

**Comment by Paladinfeng** [comment]
确实是theos环境的问题, 多谢
