### ISSUE TITLE
没效果啊   make了后  注入 和重签名  。 发完红包没效果  

### ISSUE THREAD

**Issue by Gavin123** [kevll/WeChatRedEnvelopesHelper#24]
![img_5659](https://user-images.githubusercontent.com/5095402/34554097-19ee13d0-f166-11e7-91cf-c475d08b7ceb.PNG)

**Comment by Gavin123** [comment]
系统11.2   微信版本6.6.1

**Comment by kevll** [comment]
有没有试过我打包的ipa?

**Comment by Gavin123** [comment]
刚试了下你的包，重签名后是可以的。 是不是有代码没上传完啊

**Comment by kevll** [comment]
GitHub上面代码全部都是完整的，有可能是你使用的substrate版本和我的不一致。
你可以从我签名的ipa中解压缩得到WeChat.app，然后在里面找到libsubstrate.dylib使用

**Comment by iangsb** [comment]
7天后需要重新签名吗？

**Comment by Gavin123** [comment]
@iangsb 你随便弄个证书重签下就可以了

**Comment by Gavin123** [comment]
@kevll 哥们分析了下你的代码 ，你是通过IDA  cy  reveal 等工具一步步分析出来的吗？  另外请教下除了Tweak.xm文件  其他还有两个.xm文件，你这种写法第一次看到，以前一直以为必须都放在Tweak.xm中  #

**Comment by kevll** [comment]
分析工具主要就是那几个
可以多个Tweak文件，主要看你的Makefile文件怎么写的
我的是使用这种`$(wildcard src/*.xm)`这种通配符方式，具体你可参考我的Makefile文件
