### ISSUE TITLE
安装出错（iPhone6P 11.0）

### ISSUE THREAD

**Issue by CoderFeiSu** [kevll/WeChatRedEnvelopesHelper#27]
installation.cpp:42
Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.emgrjX/extracted/Payload/WeChat.app : 0xe800800d (There was an error communicating with your device.)

**Comment by cheenbee** [comment]
iPhone 6s iOS11.2.1 亲测好使

**Comment by cheenbee** [comment]
下载最新的ipa包试试

**Comment by CoderFeiSu** [comment]
确实是最新ipa包   我在iPhone5S 8.0上面可以安装成功
