### ISSUE TITLE
iOS 10.3.3 g0blin越狱 安装后系统应用程序闪退

### ISSUE THREAD

**Issue by erickwoc** [kevll/WeChatRedEnvelopesHelper#32]
设备：iPhone 6s
系统：iOS 10.3.3
越狱：g0blin
现象：安装后首次打开微信导致微信闪退，再次打开则能正常进入微信，但其他系统应用程序包括Safari、App Store、设置等会闪退。卸载插件后恢复正常。

**Comment by kevll** [comment]
@erickwoc V2.0.0版本已发布，请尝试新版本

**Comment by erickwoc** [comment]
@kevll 棒棒哒！
