### ISSUE TITLE
没接触过这个签名工具，是和企业账号一样的作用吗？我看网上说的7天就要重新安装

### ISSUE THREAD

**Issue by jackhanm** [kevll/WeChatRedEnvelopesHelper#4]

**Comment by kevll** [comment]
和企业账号有点不一样，企业账号是一次打包签名然后可以直接分发给不同设备安装，而这种利用impactor工具安装到不同设备是每次都重新打包签名一次。这种方式7天后不需要重新安装的，我自己手机上的微信已经装了几个月了一直是可以正常使用的。
