### ISSUE TITLE
能否增加对方撤回消息后有提示呢？

### ISSUE THREAD

**Issue by palislau** [kevll/WeChatRedEnvelopesHelper#47]
现在X上完美运行，但微信对方撤回之后，本方没有任何提示，都不知道对方有没有撤回，能不能在对方撤回的时候，在本方显示一条提示信息即对方于什么时候撤回一条信息

**Comment by kevll** [comment]
下一个版本会增加，敬请期待

**Comment by pnyang0663** [comment]
你好，请问下个版本大概几时可以？

**Comment by kevll** [comment]
新版本已增加提示
