### ISSUE TITLE
Impactor 安装出现问题

### ISSUE THREAD

**Issue by pengshengsongcode** [kevll/WeChatRedEnvelopesHelper#59]
<img width="774" alt="2018-02-02 11 14 58" src="https://user-images.githubusercontent.com/18256030/35714932-88abc654-080a-11e8-8417-1a3750a3a2cc.png">

**Comment by kevll** [comment]
请参考 #8

**Comment by pengshengsongcode** [comment]
密码OK了又出别的问题了，放弃了

**Comment by kevll** [comment]
如有开发者账号，可自行签名安装，请参考[resign](https://github.com/kevll/resign)
