### ISSUE TITLE
非越狱手机试了一下，可以自动抢。

### ISSUE THREAD

**Issue by zfx5130** [kevll/WeChatRedEnvelopesHelper#6]
但是抢的速度有点慢， 对方发红包以后，过了10几秒后才提示抢到红包，有点慢

**Comment by zfx5130** [comment]
不过已经很厉害了， 感谢提供。

**Comment by kevll** [comment]
这个和手机当时的网速有很大关系的，抢到红包耗费的总时间等于收到红包消息的时间加上打开红包时间以及领取红包消耗的时间，每一步都是需要网络请求的，建议在4G环境测试

**Comment by gavin-tang** [comment]
非越狱手机
iPhone6 (11.2.1) 用 Impactor，无法安装 ipa， 错误 zip.cpp:557 cannot unzip Not a zip archive。
Impactor 是 最新的 Cydia Impactor 0.9.42。

**Comment by persenzhou** [comment]
zip.cpp:557 cannot unzip : not a zip archive

**Comment by kevll** [comment]
下载的是[这个链接](https://github.com/kevll/WeChatRedEnvelopesHelper/blob/master/ipa/WeChat-kevll.ipa)下的ipa吗？
我刚刚亲自下载了一下，是可以正常安装的

**Comment by gavin-tang** [comment]
直接 clone 的整个项目
使用的是ipa 里面的 .ipa 文件。

**Comment by kevll** [comment]
clone下来ipa文件大小是90.4MB吗？
是Mac系统还是windows的？
建议直接到[这个链接](https://github.com/kevll/WeChatRedEnvelopesHelper/blob/master/ipa/WeChat-kevll.ipa)点击Download进行下载ipa

**Comment by gavin-tang** [comment]
![49e23818-b8da-4730-84e7-4431dd47f6b2](https://user-images.githubusercontent.com/3839147/34433757-519be324-ecbc-11e7-8705-1b6de373d02e.png)
clone 下来的。

**Comment by DGLY** [comment]
大佬,试了一下抢不了啊,系统iOS 11.1.2

**Comment by kevll** [comment]
你先试试clone下来ipa的能不能修改文件名为WeChat-kevll.zip后双击解压，如果能解压就不是ipa的问题
不行试试百度网盘[下载ipa](https://pan.baidu.com/s/1o8mmMG6)  密码: vh18

**Comment by kevll** [comment]
@DGLY 你的安装成功了吗？安装成功后需要到微信的设置开启红包助手

**Comment by DGLY** [comment]
@kevll 安装成功了,设置了抢红包,然后找朋友试了一下,没有自动抢红包...是不是还要做别的操作

**Comment by kevll** [comment]
@DGLY 请安装一下最新的ipa，我做了一些优化体验更好，而且增加了指定群聊过滤功能。ipa百度网盘[下载链接](https://pan.baidu.com/s/1bKlctg)  密码: grdx </br>

**Comment by kevll** [comment]
@lightrain1002  是装的最新的ipa吗?

**Comment by lightrain1002** [comment]
应该是上一个版本，我的是iPhone6，非越狱iOS 10.3.3，ipa版本说明里好像是0.0.1。另外有个不知道算不算问题的问题，安装好你这个ipa后，我的手机上就存在两个微信，登录任意一个，另一个都会有下线提示，这个会不会跟我申请了另一个appleid绑定ipa有关？

**Comment by kevll** [comment]
@lightrain1002 其中一个微信登陆同一个账号会把手机上另外一个微信挤下线是正常的，微信是单点登陆的。
