### ISSUE TITLE
建议全部文件走GitHub

### ISSUE THREAD

**Issue by iHTCboy** [kevll/WeChatRedEnvelopesHelper#60]
百度网盘下载速度非常慢，放到GitHub吧，非越狱的ipa包，谢谢！辛苦啦！

**Comment by kevll** [comment]
我Github LFS流量用完了，所以目前暂时只能挂到百度云盘

**Comment by iHTCboy** [comment]
@kevll 好的，目前也没有更好的网盘推荐。国内可以试试 onedrive，如果有vpn建议走谷歌或dropbox。辛苦啦！

**Comment by Jifeng2015** [comment]
大神，百度云盘的下载地址是什么？ @kevll

**Comment by kevll** [comment]
@Jifeng2015 下载地址在我Github页面上

**Comment by Jifeng2015** [comment]
我找了一遍，木有看到百度云盘地址 @kevll

**Comment by kevll** [comment]
@Jifeng2015 https://pan.baidu.com/s/1mkd0ymc 密码：sfjs

**Comment by Jifeng2015** [comment]
好的，谢谢啦
