### ISSUE TITLE
大神做的两个修改版都很厉害，但是

### ISSUE THREAD

**Issue by xieao100** [kevll/WeChatRedEnvelopesHelper#61]
还有两个问题：
1、app如何更新？是否还是在GitHub里面下载然后安装替换？有检测更新的提示吗？只能手动？没有更方便的方法吗？
2、微信防止撤回是否能给出个提示？不知道对方撤回了什么啊

**Comment by xieao100** [comment]
还有个问题，开启抢红包和后台强红包比原版是不是要耗电一些？市场上面一些多开版抢红包就特别耗电，原本ios11就耗电，开抢红包本身几分钟掉一格电，这下一下掉3格，大神做的这款应该是比多开版的耗电情况要好一些的，但是感觉还是比原版的要耗电一些啊，求大神说说开启后台抢红包后耗电量如何？

**Comment by kevll** [comment]
1.如果是非越狱手机，那么只能在Github重新下载安装替换，因为是对微信可运行文件注入dylib方式，所以目前只能这么做。如果是越狱手机就不存在这个问题了，直接AppStore下载更新就行。
2.微信撤回提示下一个版本就会增加。
3.开启后台模式耗电量会稍微增加一点，不开启后台模式时耗电量和正常使用微信是一样的。如果你比较介意耗电，那么就请关闭后台模式，但是也意味着微信退到后台一段时间后就无法自动抢红包，这个你可以自行斟酌一下。
