### ISSUE TITLE
make报错，请指导一下，谢谢

### ISSUE THREAD

**Issue by p0tty-git** [kevll/WeChatRedEnvelopesHelper#63]
新手刚入门，没有修改任何文件，只想自己东西走一下流程，make时报错信息如下：
admin$ make
> Making all for tweak WeChatRedEnvelopesHelper…
==> Compiling src/LLRedEnvelopesMgr.m (armv7)…
src/LLRedEnvelopesMgr.m:364:87: error: Objective-C message has incomplete result
      type 'struct CLLocationCoordinate2D'
  ...? [[CLLocation alloc] initWithCoordinate:_virtualLocation.coordinate alt...
                                                               ^
src/WCRedEnvelopesHelper.h:273:29: note: forward declaration of 'struct
      CLLocationCoordinate2D'
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synth...
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocation.h:200:60: note: 
      passing argument to parameter 'coordinate' here
- (instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate
                                                           ^
1 error generated.
make[3]: *** [/Users/admin/Desktop/20/.theos/obj/debug/armv7/src/LLRedEnvelopesMgr.m.2f6d9a6c.o] Error 1
make[2]: *** [/Users/admin/Desktop/20/.theos/obj/debug/armv7/WeChatRedEnvelopesHelper.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [WeChatRedEnvelopesHelper.all.tweak.variables] Error 2

**Comment by p0tty-git** [comment]
补充一下
系统版本10.11.6
Xcode Version 7.1.1
theos是最新的

**Comment by p0tty-git** [comment]
更新了xcode到8.2，还是报错
> Making all for tweak WeChatRedEnvelopesHelper…
==> Compiling src/LLRedEnvelopesMgr.m (armv7)…
==> Compiling src/LLSettingController.m (armv7)…
src/LLSettingController.m:86:9: error: unexpected '@' in program
    if (@available(iOS 11, *)) {         
        ^
src/LLSettingController.m:87:39: error: property
      'contentInsetAdjustmentBehavior' not found on object of type
      'MMTableView *'
        [_tableViewInfo getTableView].contentInsetAdjustmentBehavior = U...
                                      ^
src/LLSettingController.m:87:72: error: use of undeclared identifier
      'UIScrollViewContentInsetAdjustmentAlways'
        [_tableViewInfo getTableView].contentInsetAdjustmentBehavior = UIScrollV...
                                                                       ^
3 errors generated.

**Comment by kevll** [comment]
请更新Xcode到9.0以上版本

**Comment by p0tty-git** [comment]
@kevll 更新到9.2了，果然是Xcode原因，但现在还是有一个告警
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]

**Comment by kevll** [comment]
这个警告可以忽略
