### ISSUE TITLE
IOS11.2按非越狱i方法安装ipa后进入微信(6.6.2)没有出现微信助手设置

### ISSUE THREAD

**Issue by ruanzupan** [kevll/WeChatRedEnvelopesHelper#67]
IOS11.2按非越狱i方法安装ipa后进入微信(6.6.2)没有出现微信助手设置,是为什么呢？

**Comment by kevll** [comment]
你是直接安装下载下来的ipa还是自己重新打包签名了？

**Comment by ruanzupan** [comment]
我是直接安装下载下来的ipa的。@kevll

**Comment by kevll** [comment]
你安装的是哪个版本？v2.0.1？
操作路径：微信 “设置” —-> “微信助手设置” 
另外不要和官方微信弄混了，如果你手机本身存在微信，再安装的话应该会出现两个微信。

**Comment by ruanzupan** [comment]
原来前几次我都是点到了官方的微信了，桌面果然是多了个APP的，测试可用 ! Thanks♪(･ω･)ﾉ
