### ISSUE TITLE
已安装微信会重新安装一个？

### ISSUE THREAD

**Issue by CaKum** [kevll/WeChatRedEnvelopesHelper#70]
手机上已经有微信了，又重装了一个？原本的微信无法使用么？

**Comment by kevll** [comment]
手机越狱的情况下，可以直接用官方微信
如果没越狱，那么把ipa的bundleId修改为com.tencent.xin再安装就行了(需要先删除官方微信）

**Comment by CaKum** [comment]
怎么修改呢？大神求教

**Comment by CaKum** [comment]
怎么修改呢？求大神教我我是小白，然后我是X用了这个插件后发现没有后台通知了

**Comment by CaKum** [comment]
@kevll 修改了bundleid之后还是收不到推送，有时候有时候没有

**Comment by CaKum** [comment]
@kevll 还有个小问题，就是在前台消息通知的声音好像重叠了呢

**Comment by a307502037** [comment]
@CaKum 你好，你是怎么修改的？

**Comment by kevll** [comment]
@CaKum 推送确实会有时候能收到有时候收不到，收到推送了可能是微信利用socket和服务器通信后发的一个本地推送。
声音重叠了是什么意思？
