### ISSUE TITLE
大神有联系方式吗

### ISSUE THREAD

**Issue by ljyddz1** [kevll/WeChatRedEnvelopesHelper#78]
大神我觉得你的软件非常好用 我是在叉叉助手上下载的 不知道还会不会更新 你有其他联系方式吗 微信群什么的 如果这个软件以后会持续更新的话 我们都愿意请你喝咖啡٩😛ི۶

**Comment by kevll** [comment]
最近几天就会更新一个版本
现在暂时还没有建微信群
