### ISSUE TITLE
老大,输入账号密码提示有误?鬼鬼!

### ISSUE THREAD

**Issue by jackey-jiang** [kevll/WeChatRedEnvelopesHelper#8]
error

provision.cpp:168
Please sign in with an app-specific password. You can create one at appleid.apple.com

说要我用指定的密码登录,可是我确认我使用的是正确的密码. 大佬 怎么说~

**Comment by kevll** [comment]
你的苹果账号开启了双重验证，需要使用app专用密钥
1.在Apple官网登陆你的账号，然后点击右上角账号管理(Account Settings) -> Manage my Apple ID去生成密码。
2.或者你重新注册一个苹果账号也可以的。

**Comment by jackey-jiang** [comment]
如果我重新注册,用新的账号注入,  我的手机还是用之前的 appid 可以么

**Comment by kevll** [comment]
可以的，可以直接用注册的新的苹果账号，这两个互不影响的。

**Comment by jackey-jiang** [comment]
大佬,可用,很棒!希望继续发扬艰苦奋斗的精神,话说啥时候支持6.6.1,微信更新了微信小游戏这个很重要的点!期待大佬后续!

**Comment by kevll** [comment]
@jackey-jiang V2.0.1新版本已发布，基于微信6.6.1版本
