### ISSUE TITLE
2.1.0用impactor安装报错

### ISSUE THREAD

**Issue by Fansiz** [kevll/WeChatRedEnvelopesHelper#83]
installation.cpp:42
Appex bundle at "/private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.aJDOKu/extracted/Payload/WeChat.app/PlugIns/WeChatSiriExtensionUI.appex" with identifier "com.tencent.xin.siriextensionui" does not have expected identifier prefix "com.kevll.dt."

**Comment by cscroy** [comment]
me too!

**Comment by kevll** [comment]
@Fansiz @cscroy 请重新下载Github百度云盘ipa
