### ISSUE TITLE
未越狱按照方法1安装不成功

### ISSUE THREAD

**Issue by flishqq** [kevll/WeChatRedEnvelopesHelper#84]
一直卡在这个界面
手机是ios10.3.3

![img](https://s1.ax1x.com/2018/02/14/9Y3uqg.jpg)

**Comment by flishqq** [comment]
2.1.0无法安装
换了2.0.1使用正常，应该是这个更新的问题

**Comment by kevll** [comment]
@flishqq 请重新下载Github百度云盘v2.1.0版ipa

**Comment by flishqq** [comment]
安装成功了，感谢！
