### ISSUE TITLE
6sp  11.2无法自动抢红包

### ISSUE THREAD

**Issue by LambentWu** [kevll/WeChatRedEnvelopesHelper#9]
试了11.2  无法自动抢

**Comment by SimonLing** [comment]
一样

**Comment by kevll** [comment]
请安装一下最新的ipa，我做了一些优化体验更好，而且增加了指定群聊过滤功能，已测试iOS9-iOS11系统。
ipa百度网盘[下载链接](https://pan.baidu.com/s/1bKlctg)  密码: grdx
