### ISSUE TITLE
【已解决】非越狱设备使用方法ii安装失败

### ISSUE THREAD

**Issue by muwan** [kevll/WeChatRedEnvelopesHelper#93]
步骤；
1、下载百度云的ipa，拿到两个动态库，下载xx助手上已越狱版本微信的ipa
2、用inject_dylib向越狱的ipa注入两个动态库，生成 微信_rejected.ipa
3、使用resign重新签名，生成 微信_rejected_resigned.ipa
4、用Impactor安装，安装失败了，提示：
```
installation.cpp:42 The WatchKit 2.0 app being installed contains an invalid application executable.
```
删除watch重新发包签名后，Impactor使用另一个证书，任然失败，提示

```
ipa.cpp:444 cannot find .app/Info.plist
```

想尝试下自己用最新的ipa打包，失败了，求指教

**Comment by wjg1101766085** [comment]
我自己编译注入的成功的！！

**Comment by muwan** [comment]
也是上述步骤吗？求指点啊

**Comment by wjg1101766085** [comment]
不是。

**Comment by muwan** [comment]
求指点下步骤 (｡ì _ í｡)

**Comment by wjg1101766085** [comment]
下载代码、编译、自己注入、签名打包、用xcode安装到手机

**Comment by muwan** [comment]
居然没想到用Xcode！我蠢了，多谢

**Comment by wjg1101766085** [comment]
客气了

**Comment by muwan** [comment]
还是不成功。。。Xcode提示```app does not contain an application bundle.......```

**Comment by 211Yang** [comment]
@muwan 我也是下载代码、编译、自己注入、签名打包、用xcode安装到手机，但是闪退了，请教下原因！

**Comment by 211Yang** [comment]
@wjg1101766085 我也是下载代码、编译、自己注入、签名打包、用xcode安装到手机，但是闪退了，请教下原因！

**Comment by 211Yang** [comment]
@muwan ipa.cpp:444 cannot find .app/Info.plist你这个问题我今天也碰到了，解决了，你把文件放到系统根目录下，名字用Payload，然后用命令zip -r WeChat.ipa Payload，打包成ipa包，就可以了。

**Comment by muwan** [comment]
感谢，感谢，确实是的。
最后resgin完成后，得到的ipa解压，然后把entitlements_full.plist，entitlements.plist，放到和xxx.app同一个目录下，最后用命令```zip -r WeChat.ipa Payload```

**Comment by 211Yang** [comment]
@muwan 你安装后可以正常使用吗，你这两个文件entitlements_full.plist，entitlements.plist分别是用来干嘛的

**Comment by muwan** [comment]
限制只有部分uuid才能安装

**Comment by 211Yang** [comment]
@muwan 能安装，但闪退。

**Comment by 211Yang** [comment]
@muwan 你这两个文件entitlements_full.plist，entitlements.plist里面分别是什么内容，可以发出来看下吗

**Comment by 211Yang** [comment]
@muwan 我是用另外一种方法安装的，现在用和你一样的方法安装，登录还是闪退，我微信版本是6.6.5，你是哪个版本？

**Comment by wjg1101766085** [comment]
登陆闪退是因为注入的动态库有问题！！
