### ISSUE TITLE
2.1已被官方检测

### ISSUE THREAD

**Issue by spiritwave** [kevll/WeChatRedEnvelopesHelper#96]
已被检测在非官方微信应用登录，无法登录了

**Comment by spiritwave** [comment]
是不是不能双开微信使用的原因，开发者能回答下吗

**Comment by kevll** [comment]
最近微信查的比较严，下一版本会对微信暗桩检测做处理。

**Comment by iSaury** [comment]
@kevll 大神, 新版本什么时候出来呀, 最近被检测好几次了.....谢谢啦

**Comment by iSaury** [comment]
@kevll 大神, 新版本什么时候出来呀, 最近被检测好几次了.....谢谢啦

**Comment by iSaury** [comment]
@a3946 未越狱安装的

**Comment by kevll** [comment]
V2.2已解决此问题，已对微信后台上传bundleId进行拦截处理
